"""empty message

Revision ID: 0d6e136f3c4e
Revises: 36701c375bcd
Create Date: 2020-09-06 14:56:52.328809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6e136f3c4e'
down_revision = '36701c375bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image_link')
    op.drop_column('movies', 'description')
    op.drop_column('actors', 'image_link')
    # ### end Alembic commands ###
